name: Keep App Alive

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          curl -i -f https://money-check-theta.vercel.app/api/health